[project]
name = "loading"
version = "0.1.0"
description = "Matrix exercise"
authors = [
    {name = "rajarada"}
]
requires-python = ">=3.12"
dependencies = [
]

[dependency-groups]
dev = [
    "pandas (>=3.0.2,<4.0.0)",
    "numpy (>=2.4.4,<3.0.0)",
    "matplotlib (>=3.10.9,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
